#global optflags %{optflags} -latomic

%global optflags %{optflags} -O3

Name:		rawtherapee
Version:	5.11
Release:	1
Summary:	Raw image processing software
Group:		Graphics
License:	GPLv3 and MIT and IJG
URL:		https://www.rawtherapee.com/
# Never use auto-generated by github source .tar.gz (broken). Use github tarball (.xz) or tarball below:
Source0:	https://github.com/Beep6581/RawTherapee/releases/download/%{version}/rawtherapee-%{version}.tar.xz
# Looks like no longer updated
#Source0:	https://rawtherapee.com/shared/source/%{name}-%{version}.tar.xz
Patch0:		rawtherapee-5.10-clang16.patch

BuildRequires:	cmake >= 3.5
BuildRequires:	ninja
BuildRequires:	pkgconfig(expat) >= 2.0
BuildRequires:	pkgconfig(fftw3)
BuildRequires:	pkgconfig(fftw3f)
BuildRequires:	pkgconfig(gio-2.0) >= 2.16
BuildRequires:	pkgconfig(giomm-2.4) >= 2.12
BuildRequires:	pkgconfig(glib-2.0) >= 2.16
BuildRequires:	pkgconfig(glibmm-2.4) >= 2.16
BuildRequires:	pkgconfig(gobject-2.0) >= 2.16
BuildRequires:	pkgconfig(gthread-2.0) >= 2.16
BuildRequires:	pkgconfig(gtk+-2.0)
BuildRequires:	pkgconfig(gtkmm-3.0)
BuildRequires:	pkgconfig(exiv2)
BuildRequires:	pkgconfig(lcms2)
BuildRequires:	pkgconfig(lensfun)
BuildRequires:	pkgconfig(libcanberra-gtk)
BuildRequires:	pkgconfig(libiptcdata)
BuildRequires:	pkgconfig(sigc++-2.0)
BuildRequires:  pkgconfig(librsvg-2.0)
BuildRequires:	bzip2-devel
BuildRequires:	mercurial
BuildRequires:	jpeg-devel
BuildRequires:	tiff-devel
BuildRequires:	png-devel
BuildRequires:	libgomp-devel
BuildRequires:  libatomic-devel
Requires:	hicolor-icon-theme

%description
Rawtherapee is a RAW image processing software. It gives full control over
many parameters to enhance the raw picture before finally exporting it
to some common image format.

%prep
%autosetup -p1

%build
# Force GCC due to clang crash at build
#export CC=gcc
#export CXX=g++
%cmake \
	-DBUILD_SHARED_LIBS=OFF \
	-DOPTION_OMP="ON" \
	-DWITH_BENCHMARK="ON" \
	-GNinja
%ninja_build

%install
%ninja_install -C build

# These file are taken from the root already
rm -rf %{buildroot}%{_datadir}/doc/rawtherapee

%files
%doc AUTHORS.txt RELEASE_NOTES.txt
%{_bindir}/rawtherapee
# %{_bindir}/camconst.json
%{_bindir}/rawtherapee-cli
%{_datadir}/rawtherapee
%{_datadir}/applications/%{name}.desktop
%{_datadir}/metainfo/com.rawtherapee.RawTherapee.appdata.xml
%{_iconsdir}/hicolor/*/apps/rawtherapee.png
%{_iconsdir}/hicolor/scalable/apps/rawtherapee.svg
%{_mandir}/man1/%{name}.1*
